# Site settings
title:            Kemal
email:            dogruyolserdar@gmail.com
description:      'Lightning Fast, Super Simple web framework for Crystal. Inspired by Sinatra'
baseurl:          "" # the subpath of your site, e.g. /blog
url:              "http://kemalcr.com" # the base hostname & protocol for your site
twitter_username: sdogruyol
github_username:  sdogruyol

# Build settings
markdown:         kramdown
highlighter:      rouge
permalink:        /blog/:year/:month/:day/:title/

collections:
  cookbook:
    output: true

nav_bars:
  - title: "Guide"
    url: "/guide"
  - title: "Cookbook"
    url: "/cookbook/hello_world"
  - title: "API"
    url: "/docs"
  - title: "Blog"
    url: "/blog"
  - title: "Community"
    url: "/community"
  - title: "Users"
    url: "https://github.com/kemalcr/kemal/wiki/Kemal-Users"
  - title: "Github"
    url: "https://github.com/kemalcr/kemal"


examples:
  - title: "How to connect to Database"
    url: "https://github.com/sdogruyol/kemal-pg-sample"

jsarr:
  - name: "/js/browser.js"

plugins:
  - jemoji
